config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  #get 'contacts' => 'contacts#new', as: :contacts
  #post 'contacts' => 'contacts#create', as: :create_contacts
  #get 'contacts/sent' => 'contacts#sent', as: :contacts_sent

  #get 'search' => 'search#index', as: :search

  # resources :news, only: [:index, :show]
  # namespace api do
  #   resources :status, only: :index
  # end

  get 'users/edit/index' => 'api/status#index', as: :show_type_articles, method: :get
  namespace :api do
    resources :article
  end
  resources :users, only: [:update, :edit, :destroy]
  resources :articles do
    member do
      post :edit_rating
    end
  end
  get '*slug' => 'pages#show'
  resources :pages, only: [:show]
  root to: 'articles#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :bigint(8)        not null, primary key
#  title       :string
#  user_id     :bigint(8)
#  description :text
#  category_id :bigint(8)
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Article < ApplicationRecord
  #include ActiveModel::Serialization
  belongs_to :user, dependent: :destroy
  has_many :tags, dependent: :destroy
  belongs_to :category
  has_many :images, as: :imageable, dependent: :destroy
  has_many :points
  accepts_nested_attributes_for :images, allow_destroy: true
  # validates :name, :length { :minimum 1, to_short: "name must be %{count} symbols" }
  validates :title, length: { minimum: 2 }
  validates :description, presence: true
  validates :category_id, numericality: true
#locale :ru
  state_machine :status, :initial => :inprocess do
    event :accept do
      transition [:inprocess, :disabled] => :accepted
    end
    event :disable do
      transition [:inprocess, :accepted] => :disabled
    end
    event :inprocess do
      transition [:accepted,:disabled] => :inprocess
    end
    after_transition any => :accepted do |article|
      UserMailer.accept_email(article.title, article.user.email, article.user.full_name).deliver_now
    end
    after_transition any => :disabled do |article|
      UserMailer.disable_email(article.title, article.user.email, article.user.full_name).deliver_now
    end
    after_transition any => :inprocess do |article|
      UserMailer.innprocess_email(article.title, article.user.email, article.user.full_name).deliver_now
    end
  end
  rails_admin do
    list do
      field :status, :state
      field :category
      field :user
      field :title
      field :description
      field :category
    end
   edit do
     field :status, :state
     field :title
     field :user
     field :description, :ckeditor
     field :category
  end
  state({
  events: {accept: 'btn-success', disable: 'btn-danger', inprocess: 'btn-warning'},
  states: {accept: 'label-info', accepted: 'label-success', disabled: 'label-danger', inprocess: 'label-warning'}
  #  disable: [:dead] # disable some events so they are not shown.
  })
  end
end

app/controllers/api/article_controller.rb
class Api::ArticleController < ApplicationController
  def index
    page = params[:page] || 1
    category_id = params[:category_id] || Category.first.id
    article = Article.where(category_id: category_id).page(page).per(3)
    render json: article
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
#@test = user_session
#binding.pry

  #if user_signed_in? and current_user.role == "user"
    @articles = Article.where(status: "accepted").page(params[:page]).per(10)
#  else
#    redirect_to "/admin"
#  end
  #  @article = Article.find(params[:id])
    # @article_pag=Kaminari.paginate_array(@all_article)


#@article_pag=Kaminari.paginate_array(@all_article).page(1).per(10)
  end
  def new
   @article = Article.new
   @article.images.build
   @category = Category.all
  end

  def create
      article = Article.create(article_params)
      if article.errors.any?
        flash[:error] = article.errors.full_messages.join(",")
       redirect_to new_article_path
      else
        flash[:notice] = 'Статья создана успешно'
        redirect_to article_path(article.id)
     end
end

  def edit
    @article = Article.find(params[:id])
    @category = Category.all
    @user = User.all
  end

  def show
    @article = Article.find(params[:id])
    @article_cat = Article.where(category_id: @article.category_id).sample(3)
    @raiting =  @article.points.count > 0 ? @article.points.pluck(:rating).sum.to_f / @article.points.count : 0
    @article.update_attribute(:visits, @article.visits.to_i + 1)
    @point = Point.new
  end
  def user_page
    @articles = Article.where( user_id: params[:user_id])
  end

  def category
      @article_cat_all = Article.where(category_id: params[:category_id])
  end

  def update
    @article_update = Article.find(params[:id])
     if @article_update.update(article_params)
       flash[:notice] = 'Статья обновлена успешно'
       redirect_to article_path(params[:id])
     else
       flash[:error] = @article_update.errors.full_messages.join(', ')
       redirect_to article_path(params[:id])
     end
  end

  def destroy
    if Article.find(params[:id]).destroy
      flash[:notice] = 'Статья удалена успешно'
      redirect_to root_path
    else
      flash[:error] = 'Статья не удалена'
      redirect_to article_path(params[:id])
    end
  end

  def edit_rating
    if Point.create(params[:point].permit!)
      flash[:notice] = "Спасибо за оценку."
      redirect_to article_path(params[:point][:article_id])
    else
      flash[:error] = "Оценка не учтена."
      redirect_to article_path(params[:point][:article_id])
    end
  end


  private

  def article_params
    params.require(:article).permit(:user_id ,:title, :description, :category_id, images_attributes:[:image])
  end




end

app/views/articles/category.slim
|Привет это не факт что нужная вьюха для демонстарции статей по 1 категории
= render partial: "articles/blocks/index-article", collection: @article_cat_all, as: :item

app/views/articles/edit.slim
| Привет это вьюха article/edit

/ = simple_form_for @article, as: :article, method: :put, url: article_path do |f|
= simple_form_for @article do |f|
  | Название статьи
  = f.input :title
  = f.input :description, label: "Краткое описание 'шедевра'"
  //= f.input :user_id, label: "id тела написавшего это..."
  = f.input :category_id, collection: @category, selected: @article.category_id
  / = binding.pry
  /-unless :images.nil?
  = f.simple_fields_for :images do |field|
    = field.file_field :image, as: :file
  / - @article.images.each do |img|
  //


  //= f.input :category, collection: "#{@category}"
  //= f.input :category, label: "сорт говна она же категория(в душе не ебу как отобразить по нормальному)"
  //= f.input :status, label: "Статус"
  = f.button :submit, "Сохранить"
  / , class: 'btn btn-outline-primary'
end

= button_to 'Назад', article_path(@article),method: :get

app/views/articles/index.slim
| Привет это вьюха article/index

.articles
  = render partial: "articles/blocks/index-article", collection: @articles.order(id: :desc), as: :item
= paginate @articles

app/views/articles/new.slim
= form_with model: @article do |f|
  | Название
  = f.text_field :title
  p
  | Описание
  = f.text_area :description
  p
  | Категория
  = f.collection_select(:category_id ,Category.all, :id, :title)
  p
  = f.simple_fields_for :images do |field|
    = field.file_field :image, as: :file
  = f.hidden_field :user_id, value: current_user.id
  //= binding.pry
  = f.submit "Create"
  //- test_array = Category.all.map { |cat| [cat.title, cat.id] }
//  = f.hidden_field :user_id
//= binding.pry

app/views/articles/show.slim
| Привет это вьюха article/show
p
|ИД Титул Пользователь Описание Кaтегория
t
p
.category
  .category__info
    / p = link_to "#{@article.category.title}", show_category_path(@article.category_id)
    p = @article.title
    p Автор: #{@article.user.full_name unless @article.user.nil?}
    p = @article.description
    p Тэги:
    - @article.tags.each do |tag|
      = tag.text
    p Кол-во просмотров: #{@article.visits}
    - if @article.images.present?
      p Картинки
      - @article.images.each do |img|
        = image_tag(img.image.url(:medium), :alt => img.name)
    .category__controls
      = button_to 'Редактировать', edit_article_path(@article), method: :get if can? :update, @article
      = button_to 'Удалить', article_path(@article),
                             method: :delete,
                             data: { confirm: 'Вы уверены?' }
      = button_to 'Назад', articles_path, method: :get
      / - @article.points.each do |p|
      /   - @array = [] << p.rating
      /   = @array.sum
      p Средняя оценка статьи: #{@raiting}
      - if current_user.present? and current_user.article_points?(@article.id)
        = simple_form_for @point, url: edit_rating_article_path(@article.id) do |r|
          = r.hidden_field :user_id, value: current_user.id
          = r.hidden_field :article_id, value: @article.id
          = r.input :rating
          = r.button :submit,'Оценить'
      = link_to 'Создать', article_path()
      / = button_to 'Показать_больше', e_h_article_path, method: :get ,action: :e_h
  .category__articles
    p Статьи этой категории
    = render partial: "articles/blocks/index-article", collection: @article_cat, as: :item