config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  #get 'contacts' => 'contacts#new', as: :contacts
  #post 'contacts' => 'contacts#create', as: :create_contacts
  #get 'contacts/sent' => 'contacts#sent', as: :contacts_sent

  #get 'search' => 'search#index', as: :search

  # resources :news, only: [:index, :show]
  # namespace api do
  #   resources :status, only: :index
  # end

  get 'users/edit/index' => 'api/status#index', as: :show_type_articles, method: :get
  namespace :api do
    resources :article
  end
  resources :users, only: [:update, :edit, :destroy]
  resources :articles do
    member do
      post :edit_rating
    end
  end
  get '*slug' => 'pages#show'
  resources :pages, only: [:show]
  root to: 'articles#index'
end

app/views/blocks/_footer.slim
footer.footer
  | (c) #{Date.today.year}

app/views/blocks/_header.slim
header.header
  / = render_navigation &navigation(:main)

  - if current_user.nil?
    = link_to " LogIn ", new_user_session_path, class: "logIn"
    = link_to " Registration", new_user_registration_path, class: 'registration'
  - else
    = link_to "Create", new_article_path, class: 'registration'
    = link_to ' Logout ', destroy_user_session_path,  :method=>'delete', class: 'logout'
    = link_to 'Profile', edit_user_path(current_user.id), class: 'logIn'
    / = link_to "Личный кабинет", new_article_path, class: 'registration'
  //  = link_to " Редактировать", edit_user_registration_path, class: 'registration'